# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X3hkGWLGHMGG0J3b4uQ70eqwZsnNJlna
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import joblib

pipeline = joblib.load('rf_lbw_pipeline.pkl')
THRESHOLD = 0.37

st.title('LBW Risk Prediction Dashboard')
st.write('Predict Low Birth Weight risk and get intervention recommendations.')

inputs = {}
inputs['Pregnancy_Months'] = st.number_input('Pregnancy Months', 1, 10, 9)
inputs['Mother_height'] = st.number_input('Mother Height (cm)', 120, 200, 160)
inputs['Mother_weight'] = st.number_input('Mother Weight (kg)', 30, 150, 60)
inputs['Preceding_birth_interval(months)'] = st.number_input('Preceding Birth Interval (months)', 0, 120, 18)
inputs['MalFansidar_Frequecy'] = st.number_input('Malaria Fansidar Frequency', 0, 10, 2)
inputs['Mother_Age'] = st.number_input('Mother Age', 10, 50, 28)
inputs['Educational_attainment'] = st.selectbox('Educational Attainment', ['No_Eductaion', 'Primary', 'Secondary', 'Higher'])
inputs['Residence'] = st.selectbox('Residence', ['Rural', 'Urban', 'Non_Dejure'])
inputs['Days_Tablets_taken'] = st.number_input('Days Tablets Taken', 0, 365, 90)
inputs['Partner_Age'] = st.number_input('Partner Age', 10, 80, 32)
inputs['Maternal_Dewormer'] = st.selectbox('Maternal Dewormer', ['Yes', 'No'])
inputs['Wealth_index'] = st.selectbox('Wealth Index', ['Poorest', 'Poorer', 'Middle', 'Richer', 'Richest'])
inputs['ANC_Visits'] = st.number_input('ANC Visits', 0, 20, 4)
inputs['ANC1_Timing'] = st.number_input('ANC1 Timing (weeks)', 0, 40, 12)
inputs['Worked_Last_12months'] = st.selectbox('Worked Last 12 Months', ['Yes', 'No'])
inputs['Birth_order_number'] = st.number_input('Birth Order Number', 1, 20, 2)
inputs['Occupation'] = st.selectbox('Occupation', ['Unskilled_Manual', 'Professional', 'Entrepreneurship', 'Not_Working'])
inputs['Partner_Education'] = st.selectbox('Partner Education', ['No_Eductaion', 'Primary', 'Secondary', 'Higher'])
inputs['Sex_child'] = st.selectbox('Sex of Child', [0, 1])  # 0=Male, 1=Female

input_df = pd.DataFrame([inputs])

if st.button('Predict Risk'):
    risk = pipeline.predict_proba(input_df)[0][1]
    st.write(f'Predicted LBW Risk: {risk:.3f}')

    if risk >= THRESHOLD:
        st.warning('High risk of Low Birth Weight detected.')
        st.info('Recommended Interventions:')
        st.markdown(
            '- Ensure regular antenatal care visits.\n'
            '- Take iron supplements and malaria prophylaxis as advised.\n'
            '- Nutritional support to mother.\n'
            '- Monitor fetal growth closely.\n'
            '- Educate on birth spacing and family planning.'
        )
    else:
        st.success('Low risk of Low Birth Weight.')
        st.write('Continue standard antenatal care.')
